language: node_js
node_js:
  - '7.9.0'
script:
  - npm run test
  - npm run packbundle
before_install:
  - openssl aes-256-cbc -K $encrypted_2c456f34f8c3_key -iv $encrypted_2c456f34f8c3_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 120.25.217.56\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - npm prune --production
  - mv ./product ./node_modules ./package.json ~/ && rm -rf * && mv ~/product ~/node_modules ~/package.json ./ && tar -jcf cache.tar.bz2 *
  - tar -jcf cache.tar.bz2 *
  - scp cache.tar.bz2 root@120.25.217.56:~/
  - ssh root@120.25.217.56 'rm -rf ~/MicroServer/Note'
  - ssh root@120.25.217.56 'mkdir -p Note && tar -jxf cache.tar.bz2 -C Note'
  - ssh root@120.25.217.56 'mv Note ~/MicroServer/'
  - ssh root@120.25.217.56 'cd MicroServer/Note && npm start'
  - rm -rf ~/.ssh

